# Generated by Django 3.0.7 on 2021-05-28 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210528_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person_information',
            old_name='Full_name',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='person_information',
            old_name='Other_name',
            new_name='Last_name',
        ),
        migrations.AlterField(
            model_name='person_information',
            name='Adding_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 28, 15, 38, 14, 547704)),
        ),
    ]
