# Generated by Django 3.0.7 on 2021-05-28 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210528_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_information',
            name='Other_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person_information',
            name='Adding_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 28, 15, 41, 4, 224807)),
        ),
    ]
